name: "VGG11"

train:
  batch_size: 128
  epochs: 100
  lr: 0.05
  device: "cuda:1"

log:
  log_base_dir: "/data/data1/model_log"
  desc: "file"
  file: "log.txt"

model:
  save_dir: "/data/data1/model_save"

checkpoint_path: "/data/data1/checkpoint"